### PR TITLE
update gradle

### PR DESCRIPTION
**Pull request by Oshuremy**

### CODE REVIEW

**Comment by nex3z** [comment]
Thanks for the PR. But the [bintray-release](https://github.com/novoda/bintray-release) plugin used in this project is [not compatible with gradle 6.1.1 yet](https://github.com/novoda/bintray-release/issues/323), so the project will keep using gradle 5.x for now.

**Comment by Oshuremy** [comment]
Can you quickly explain me the differents ways to upload a project ?

**Comment by nex3z** [comment]
To publish artifacts to Bintray, [bintray-release](https://github.com/novoda/bintray-release) seems to be the easiest way, but the plugin does not support gradle 6.x yet. [gradle-bintray-plugin](https://github.com/bintray/gradle-bintray-plugin/) is much more up to date but also needs more configuration.

There is also [Maven Publish plugin](https://developer.android.com/studio/build/maven-publish-plugin) to publish artifacts to maven.

**Comment by panpf** [comment]
I have modified some codes on the basis of this library to support Gradle 6.0+ and Android Gradle Plugin 4.0+, and then released a brand new library, you can try to see if it can solve your problem, https://github.com/panpf/bintray-publish

**Comment by nex3z** [comment]
> I have modified some codes on the basis of this library to support Gradle 6.0+ and Android Gradle Plugin 4.0+, and then released a brand new library, you can try to see if it can solve your problem, https://github.com/panpf/bintray-publish

Works like a charm!

**Pull request closed without merging**
